[package]
name = "matcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.1"
crossbeam-channel = "0.5.2"
regex = "1.5.4"
lazy_static = "1.4.0"
csv = "1.1.6"
num_cpus = "1.13.1"
